name: Test, Build and Test - MAIN

on: 
  push:
    branches:
      - master
      - main

jobs:
  Testing_Code_Quality: 
    runs-on: ubuntu-22.04
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      #instalando dependencias das libraries
      - name: Installing Dependencies
        run: |
          sudo apt-get update && sudo apt-get install build-essential
          sudo apt install cmake libgtest-dev googletest -y
          sudo apt install clang-15 clang-tidy-15 clang-format-15 ninja-build -y
          sudo apt install libpoco-dev -y

      - name: Build project
        env:
          CC: /usr/bin/clang-15
          CXX: /usr/bin/clang++-15
        run: |
          export CURRENT_SOURCE_DIR=$(pwd)
          mkdir -p build && cd build
          export CURRENT_BUILD_DIR=$(pwd)
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE:STRING=Release
          cmake --build . --config Release --target all -j $(nproc) --

      - name: Test project
        env:
          CC: /usr/bin/clang-15
          CXX: /usr/bin/clang++-15
        run: |
          cd build
          # ctest -j 20 -C Release -T test --output-on-failure

      - name: Upload Artifacts
        if: ${{ failure() }} || ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: ws_server
          path: build/bin/ws_server
